"""teams and players tables

Revision ID: 428281c6fa0f
Revises: bef0d725441a
Create Date: 2018-10-29 16:41:34.248658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428281c6fa0f'
down_revision = 'bef0d725441a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_teamname'), 'team', ['teamname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_teamname'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
